[2025-04-02T20:19:29.050+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: Weather_Proj.Create_Cassandra_schema manual__2025-04-02T20:13:58.179770+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
